#!/bin/bash

CBITPOS=51
POLICY=0xb0000

PATH="/data/$USER/amdsev/usr/bin:$PATH"
UEFI_CODE=/data/jiamin/amdsev/edk2-stable202505/OVMF.fd
UEFI_CODE=/data/jiamin/amdsev/usr/share/qemu/OVMF.fd

# CDROM_FILE=/data/jiamin/ubuntu-24.04.1-live-server-amd64.iso

# DISK=ubuntu-disk.img

set -euox pipefail

# DISK_BASE=/data/jiamin/ubuntu-24.04-server-cloudimg-amd64.img

DISK_BASE=/data/jiamin/Fedora-Server-Guest-Generic-42-1.1.x86_64.qcow2
DISK_OVERLAY=/tmp/fedora-overlay.qcow2
if [ ! -f $DISK_OVERLAY ]; then
    qemu-img create -f qcow2 -b $DISK_BASE -F qcow2 $DISK_OVERLAY 40G
fi

if [ ! -f cloud-init/seed.img ]; then
    cloud-localds cloud-init/seed.img cloud-init/user-data
fi

# exec sudo $(which qemu-system-x86_64) \
#     -nographic \
#     -enable-kvm \
#     -cpu EPYC \
#     -machine q35 \
#     -smp 4,maxcpus=255 \
#     -m 2048M,slots=5,maxmem=10240M \
#     -drive file=cloud-init/seed.img,index=1,media=cdrom \
#     -netdev user,id=vmnic,hostfwd=tcp::2222-:22 \
#     -device virtio-net-pci,disable-legacy=on,iommu_platform=true,netdev=vmnic,romfile= \
#     -device virtio-rng-pci \
#     -drive file=$DISK,if=none,id=disk0,format=qcow2 \
#     -device virtio-scsi-pci,id=scsi0,disable-legacy=on,iommu_platform=true \
#     -device scsi-hd,drive=disk0

exec sudo $(which qemu-system-x86_64) \
    -enable-kvm \
    -cpu EPYC \
    -machine q35 \
    -smp 4,maxcpus=255 \
    -m 2048M,slots=5,maxmem=10240M \
    -no-reboot \
    -drive file=cloud-init/seed.img,index=1,media=cdrom \
    -netdev user,id=vmnic,hostfwd=tcp::2222-:22 \
    -device virtio-net-pci,disable-legacy=on,iommu_platform=true,netdev=vmnic,romfile= \
    -device virtio-rng-pci \
    -drive file=$DISK_OVERLAY,if=none,id=disk0,format=qcow2 \
    -device virtio-scsi-pci,id=scsi0,disable-legacy=on,iommu_platform=true \
    -device scsi-hd,drive=disk0 \
    -bios $UEFI_CODE \
    -machine confidential-guest-support=sev0,vmport=off \
    -object memory-backend-memfd,id=ram1,size=2048M,share=true,prealloc=false \
    -machine memory-backend=ram1 \
    -object sev-snp-guest,id=sev0,policy=0x30000,cbitpos=51,reduced-phys-bits=1 \
    -nographic | tee /home/jiamin/AMDSEV/qemu.stdout
